server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: management-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fanmengmeng/cloud
          searchPaths: /

management:
  endpoints:
    web:
      exposure:
        include: '*'