server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: management-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fanmengmeng/cloud
          searchPaths: /
    stream:
      bindings:
        itemsChannel:
          binder: rabbit
          destination: item.exchange
          group: myqueue
          contentType: application/json

  rabbitmq:
    addresses: http://127.0.0.1:5672
    username: guest
    password: guest
    virtual-host: /

management:
  endpoints:
    web:
      exposure:
        include: '*'