server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: management-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fanmengmeng/cloud
          searchPaths: /
    stream:
      bindings:
        input:
          destination: queue.log.messages
          binder: rabbit
          group: logMessageConsumers
        output:
          destination: queue.pretty.log.messages
          binder: local_rabbit
        binders:
          defaultRabbit:
            type: rabbit
            environment:
              spring:
                rabbitmq:
                  host: 127.0.0.1
                  port: 5672
                  username: guest
                  password: guest
                  virtual-host: /

management:
  endpoints:
    web:
      exposure:
        include: '*'