server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: management-producer
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
          min-partition-count: 1
      bindings:
        output:
          destination: mytopic
          content-type: text/plain
          producer:
            partitionCount: 1



